### ISSUE TITLE
Error when passing instances as list of numbers

### ISSUE THREAD

**Issue by ndangtt** [auto-optimization/iraceplot#32]
When calling irace via `python`, users can pass in `scenario["instances"]` as a list of numeric values instead of a list of strings:

```
scenario = dict(
    instances = np.arange(1),
    maxExperiments = 180)
```

And the example above would result in an error with the following line when `report` function is called:
https://github.com/auto-optimization/iraceplot/blob/5b5222582a72e2ee45eca95c6d05081f2a9cdf52/inst/template/report_html.Rmd#L110

```
! Problem while computing `seeds = seeds_by_instance[instance]`.
✖ `seeds` must be size 1, not 0.
```
I see that `seeds_by_instance[0]` causes the error, and if I do `seeds_by_instance["0"]` then it's fine. 

I'm wondering if this issue is only specific to `iracepy` and won't happen with normal irace. If that is the case perhaps we can just modify `iracepy` to make sure `scenario["instances"]` is converted to list of strings. Otherwise it can be converted within iraceplot instead.

I attach here the example `.Rdata` file (generated from Deyao's experiments) to reproduce the issue.

[cplex-region100.Rdata.txt](https://github.com/auto-optimization/iraceplot/files/10147478/cplex-region100.Rdata.txt)

**Comment by MLopez-Ibanez** [comment]
Hi, I fixed the problem with numeric values as instances but the dataset that you attached is very strange. There is only one instance:
```
> x$scenario$instances
[1] 0
```

Is that correct?

**Comment by ndangtt** [comment]
Hi Manuel,

Thank you very much for fixing it! 

The data is a simple meta-irace experiment we had with one surrogate, so that's why there is only one instance (one surrogate). We should not pass `0` as the instance anyway, but it was just a simplified test experiment Deyao is doing, and we happen to see that issue so I thought I'd report it here :)
